### ISSUE TITLE
[BUG] openssl ciphererror

### ISSUE THREAD

**Issue by Sparkkkkie** [gushmazuko/metasploit_in_termux#121]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**
After a successfully installation, when I use the command msfconsole, i get this error: `initialize': unsupported (OpenSSL::Cipher::CipherError)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: oppo a74 5g
 - OS: Android 11/Coloros 11.1

**Comment by dedshit** [comment]
its so annoying let me do pr

**Comment by noobyysauraj** [comment]
> **Important** Do not duplicate, search your issue before creating one!
> 
> **Describe the bug** After a successfully installation, when I use the command msfconsole, i get this error: `initialize': unsupported (OpenSSL::Cipher::CipherError)
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: oppo a74 5g
> * OS: Android 11/Coloros 11.1



> **Important** Do not duplicate, search your issue before creating one!
> 
> **Describe the bug** After a successfully installation, when I use the command msfconsole, i get this error: `initialize': unsupported (OpenSSL::Cipher::CipherError)
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: oppo a74 5g
> * OS: Android 11/Coloros 11.1

Can confirm the same....

`~ $ msfconsole
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `initialize': unsupported (OpenSSL::Cipher::CipherError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `included'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:14:in `include'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:14:in `<class:BlowfishCbc>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:9:in `<class:EncryptionAlgorithm>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:8:in `<class:Transport>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:7:in `<module:HrrRbSsh>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:6:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm.rb:19:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/iv_computable.rb:5:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/diffie_hellman.rb:7:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/diffie_hellman_group1_sha1.rb:4:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport.rb:15:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh.rb:15:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:146:in `default_version_string'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:40:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/sessions/command_shell_options.rb:16:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:16:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:95:in `new'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:95:in `block (2 levels) in recalculate'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:93:in `each_pair'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:93:in `block in recalculate'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:73:in `each_pair'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:73:in `recalculate'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/modules/loader/base.rb:258:in `block in load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/loading.rb:170:in `block in load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/driver.rb:160:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `new'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `driver'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'`

Complete log...

**Comment by noobyysauraj** [comment]
[This worked.....](https://github.com/gushmazuko/metasploit_in_termux/issues/111#issuecomment-1068685903) 


Thanks @dedshit

**Comment by Starboyop** [comment]
Can you plz give me some easy method to fix the bug i cant understand your method anyone plz help

**Comment by noobyysauraj** [comment]
> Can you plz give me some easy method to fix the bug i cant understand your method anyone plz help

Isn't that just a copy paste?

```
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
```

**Comment by dedshit** [comment]
> > Can you plz give me some easy method to fix the bug i cant understand your method anyone plz help
> 
> Isn't that just a copy paste?
> 
> ```
> sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
> ```
> 
> Just copy paste, and if you ever wonder what is does, then it just comment out few lines in `ecdsa_sha2_nistp521.rb` and `functionable.rb`



dont spoonfeed them let them try to understand

**Comment by ankit383** [comment]
Thanks bro , it's worked for me

**Comment by noobyysauraj** [comment]
> > > Can you plz give me some easy method to fix the bug i cant understand your method anyone plz help
> > 
> > 
> > Isn't that just a copy paste?
> > ```
> > sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just copy paste, and if you ever wonder what is does, then it just comment out few lines in `ecdsa_sha2_nistp521.rb` and `functionable.rb`
> 
> dont spoonfeed them let them try to understand

Yah true, they don't even do a proper research. That's why this issue is still open 🙃. However thanks for the fix.....

**Comment by Adia12528** [comment]
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb


This is not spoonfeed we just stuck in this problem

**Comment by dedshit** [comment]
> sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
> 
> This is not spoonfeed we just stuck in this problem

what problem

**Comment by dedshit** [comment]
> > sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
> > This is not spoonfeed we just stuck in this problem
> 
> what problem



> sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
> 
> This is not spoonfeed we just stuck in this problem

so you are telling just copy paste itself difficult task ?

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08

**Comment by MMsudo20** [comment]
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb


I tried it and it does not work

sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb: No such file or directory

Anyone help

**Comment by noobyysauraj** [comment]
> sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
> 
> I tried it and it does not work
> 
> sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb: No such file or directory sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb: No such file or directory sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb: No such file or directory
> 
> Anyone help

This issue is already fixed [here.](https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08)

**Comment by zontak** [comment]
The same here.. 

sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb: No such file or directory

I thought that this problem was in my Kali, but then I installed Ubuntu 22.04 and the problem is the same ;(

**Comment by zontak** [comment]
> 

root@# msfconsole
/var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `initialize': unsupported (OpenSSL::Cipher::CipherError)
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `new'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `included'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:14:in `include'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:14:in `<class:BlowfishCbc>'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:9:in `<class:EncryptionAlgorithm>'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:8:in `<class:Transport>'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:7:in `<module:HrrRbSsh>'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:6:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm.rb:19:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/iv_computable.rb:5:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/diffie_hellman.rb:7:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/diffie_hellman_group1_sha1.rb:4:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm.rb:17:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport.rb:15:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh.rb:15:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in `<top (required)>'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:146:in `default_version_string'
	from /opt/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:40:in `initialize'
	from /opt/metasploit-framework/lib/msf/base/sessions/command_shell_options.rb:16:in `initialize'
	from /opt/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:16:in `initialize'
	from /opt/metasploit-framework/lib/msf/core/payload_set.rb:95:in `new'
	from /opt/metasploit-framework/lib/msf/core/payload_set.rb:95:in `block (2 levels) in recalculate'
	from /opt/metasploit-framework/lib/msf/core/payload_set.rb:93:in `each_pair'
	from /opt/metasploit-framework/lib/msf/core/payload_set.rb:93:in `block in recalculate'
	from /opt/metasploit-framework/lib/msf/core/payload_set.rb:73:in `each_pair'
	from /opt/metasploit-framework/lib/msf/core/payload_set.rb:73:in `recalculate'
	from /opt/metasploit-framework/lib/msf/core/modules/loader/base.rb:258:in `block in load_modules'
	from /opt/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `each'
	from /opt/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `load_modules'
	from /opt/metasploit-framework/lib/msf/core/module_manager/loading.rb:170:in `block in load_modules'
	from /opt/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `each'
	from /opt/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `load_modules'
	from /opt/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	from /opt/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	from /opt/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	from /opt/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
	from /opt/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
	from /opt/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
	from /opt/metasploit-framework/lib/msf/ui/console/driver.rb:160:in `initialize'
	from /opt/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `new'
	from /opt/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `driver'
	from /opt/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/local/bin/msfconsole:23:in `<main>'
root@# sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb: No such file or directory
root@# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04

**Comment by Nour963** [comment]
For anyone still having this error and running @dedshit solution isn't working, it is because the files he is modifying are on a different path folder than yours
So execute msfconsole and when it prints the OpenSSL error, read carefully where is the 'hrr_rb_ssh' root  folder
Here's my error:
`/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb`
so instead of  running sed command on /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb, it should be `/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb for me`
